services:
  fluentbit:
    image: fluent/fluent-bit:3.1.9
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - LOKI_HOST=${LOKI_HOST}
      - LOKI_USER=${LOKI_USER}
      - LOKI_PASSWORD=${LOKI_PASSWORD}
    volumes:
      - type: bind
        source: ./fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    networks:
      - running_man

networks:
  running_man:
    external: true
