CREATE TABLE "user" (
  id BIGINT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  subscription_expired_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE TABLE library (
  id BIGINT PRIMARY KEY,
  year INT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE TABLE video (
  id UUID PRIMARY KEY,
  library_year INT NOT NULL,
  episode INT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMPTZ NULL,

  CONSTRAINT fk_video_library_year
    FOREIGN KEY (library_year)
    REFERENCES library(year)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE invoice (
  id UUID PRIMARY KEY,
  user_id BIGINT NOT NULL,
  ref_id VARCHAR(255) NOT NULL,
  total_amount INT NOT NULL CHECK (total_amount >= 0),
  qr_url VARCHAR(255) NOT NULL,
  expired_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMPTZ NULL,

  CONSTRAINT fk_invoice_user_id
    FOREIGN KEY (user_id)
    REFERENCES "user"(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE payment (
  id VARCHAR(255) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  invoice_id UUID UNIQUE NOT NULL,
  amount_paid INT NOT NULL CHECK (amount_paid >= 0),
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMPTZ NULL,

  CONSTRAINT fk_payment_user_id
    FOREIGN KEY (user_id)
    REFERENCES "user"(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_payment_invoice_id
    FOREIGN KEY (invoice_id)
    REFERENCES invoice(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);