services:
  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    restart: unless-stopped
    networks:
      - running_man

  webhook:
    image: mdayat/running-man-webhook:${RUNNING_MAN_WEBHOOK_TAG}
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        tag: webhook-service
        fluentd-sub-second-precision: "true"
    depends_on:
      - nginx
    restart: on-failure
    networks:
      - running_man

networks:
  running_man:
    external: true
