// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	UserID                 int64 `json:"user_id"`
	RunningManVideoEpisode int32 `json:"running_man_video_episode"`
}

type Invoice struct {
	ID                     pgtype.UUID        `json:"id"`
	UserID                 int64              `json:"user_id"`
	RunningManVideoEpisode int32              `json:"running_man_video_episode"`
	Amount                 int32              `json:"amount"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ExpiredAt              pgtype.Timestamptz `json:"expired_at"`
}

type Payment struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	InvoiceID pgtype.UUID        `json:"invoice_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RunningManLibrary struct {
	ID        int64              `json:"id"`
	Year      int32              `json:"year"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RunningManVideo struct {
	ID                    pgtype.UUID        `json:"id"`
	RunningManLibraryYear int32              `json:"running_man_library_year"`
	Episode               int32              `json:"episode"`
	Price                 int32              `json:"price"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	FirstName string             `json:"first_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
