services:
  bot:
    image: mdayat/running-man-bot:${RUNNING_MAN_BOT_TAG}
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: bot-service
        fluentd-sub-second-precision: "true"
    restart: on-failure
