services:
  bot:
    image: mdayat/running-man-bot:${RUNNING_MAN_BOT_TAG}
    logging:
      driver: fluentd
      options:
        tag: bot-service
        fluentd-sub-second-precision: "true"
    restart: on-failure
    networks:
      - running_man

networks:
  running_man:
    external: true
