name: Bot Code Quality Checks

on:
  push:
    paths:
      - "bot/**"
    branches:
      - main
  pull_request:
    paths:
      - "bot/**"
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "bot/go.mod"

      - name: Verify dependencies
        run: go mod verify
        working-directory: bot

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        working-directory: bot

      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: bot

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          work-dir: "bot"
          go-version-file: "go.mod"
          go-package: ./...

      - name: Run revive
        uses: morphy2k/revive-action@v2
        with:
          config: revive.toml
          path: ./bot/...
          fail-on-any: true
